# Generated by Django 4.1.7 on 2023-02-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'product', 'verbose_name_plural': 'product'},
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(max_length=10),
        ),
    ]
